import type {
  EventApplication,
  GymEvent,
  TrialApplication,
} from "@/lib/admin-types";

const trial = (
  id: string,
  overrides: Partial<TrialApplication> & {
    data: TrialApplication["data"];
  },
): TrialApplication => ({
  id,
  status: "new",
  submittedAt: "2026-06-10T10:00:00.000Z",
  ...overrides,
});

export const initialTrialApplications: TrialApplication[] = [
  trial("t1", {
    status: "new",
    submittedAt: "2026-06-16T14:30:00.000Z",
    data: {
      applicant_type: "adult",
      child_count: 0,
      children: [],
      kid_goals: [],
      kid_goals_other: "",
      has_martial_arts_experience: false,
      belt: null,
      belt_other: null,
      adult_goals: ["try-something-new", "get-fit"],
      adult_goals_other: "Looking for evening classes after work.",
      adult_count: 1,
      has_read_about_bjj: true,
      found_via: ["instagram"],
      first_name: "Marco",
      last_name: "Steiner",
      email: "marco.steiner@email.ch",
      phone: "+41791234567",
      whatsapp_preferred: true,
      additional_notes: "Complete beginner, no sports background.",
      best_time_to_reach: "afternoon",
      submitted_at: "2026-06-16T14:30:00.000Z",
    },
  }),
  trial("t2", {
    status: "new",
    submittedAt: "2026-06-15T09:15:00.000Z",
    data: {
      applicant_type: "kids",
      child_count: 2,
      children: [
        { firstName: "Lina", lastName: "Weber", ageBand: "6-9" },
        { firstName: "Noah", lastName: "Weber", ageBand: "10-13" },
      ],
      kid_goals: ["discipline", "fitness", "self-defence"],
      kid_goals_other: "Both kids are very energetic.",
      has_martial_arts_experience: null,
      belt: null,
      belt_other: null,
      adult_goals: [],
      adult_goals_other: "",
      adult_count: 1,
      has_read_about_bjj: false,
      found_via: ["friend"],
      first_name: "Sarah",
      last_name: "Weber",
      email: "s.weber@email.ch",
      phone: "+41792345678",
      whatsapp_preferred: false,
      additional_notes: null,
      best_time_to_reach: "late-morning",
      submitted_at: "2026-06-15T09:15:00.000Z",
    },
  }),
  trial("t3", {
    status: "scheduled",
    scheduledTrialDate: "2026-06-22",
    submittedAt: "2026-06-12T16:00:00.000Z",
    data: {
      applicant_type: "adult",
      child_count: 0,
      children: [],
      kid_goals: [],
      kid_goals_other: "",
      has_martial_arts_experience: true,
      belt: "blue",
      belt_other: null,
      adult_goals: ["push-my-game", "competitions"],
      adult_goals_other: "Training at another gym, looking to switch.",
      adult_count: 1,
      has_read_about_bjj: null,
      found_via: ["google"],
      first_name: "Thomas",
      last_name: "Keller",
      email: "t.keller@email.ch",
      phone: "+41793456789",
      whatsapp_preferred: true,
      additional_notes: "Blue belt, 2 years experience.",
      best_time_to_reach: "late-evening",
      submitted_at: "2026-06-12T16:00:00.000Z",
    },
  }),
  trial("t4", {
    status: "scheduled",
    scheduledTrialDate: "2026-06-14",
    submittedAt: "2026-06-08T11:00:00.000Z",
    data: {
      applicant_type: "family",
      child_count: 1,
      children: [{ firstName: "Emma", lastName: "Brunner", ageBand: "10-13" }],
      kid_goals: ["community", "connections"],
      kid_goals_other: "",
      has_martial_arts_experience: false,
      belt: null,
      belt_other: null,
      adult_goals: ["find-community", "get-fit"],
      adult_goals_other: "Parent wants to train alongside daughter.",
      adult_count: 1,
      has_read_about_bjj: true,
      found_via: ["facebook", "friend"],
      first_name: "Anna",
      last_name: "Brunner",
      email: "a.brunner@email.ch",
      phone: "+41794567890",
      whatsapp_preferred: true,
      additional_notes: "Family trial preferred on Wednesday.",
      best_time_to_reach: "midday",
      submitted_at: "2026-06-08T11:00:00.000Z",
    },
  }),
  trial("t5", {
    status: "scheduled",
    scheduledTrialDate: "2026-06-10",
    submittedAt: "2026-06-01T08:30:00.000Z",
    data: {
      applicant_type: "adult",
      child_count: 0,
      children: [],
      kid_goals: [],
      kid_goals_other: "",
      has_martial_arts_experience: false,
      belt: null,
      belt_other: null,
      adult_goals: ["defend-myself"],
      adult_goals_other: "",
      adult_count: 1,
      has_read_about_bjj: true,
      found_via: ["google"],
      first_name: "Luca",
      last_name: "Meier",
      email: "l.meier@email.ch",
      phone: "+41795678901",
      whatsapp_preferred: false,
      additional_notes: null,
      best_time_to_reach: "late-morning",
      submitted_at: "2026-06-01T08:30:00.000Z",
    },
  }),
  trial("t6", {
    status: "new",
    submittedAt: "2026-06-17T07:45:00.000Z",
    data: {
      applicant_type: "kids",
      child_count: 1,
      children: [{ firstName: "Leo", lastName: "Fischer", ageBand: "6-9" }],
      kid_goals: ["bullying", "self-defence", "support-child"],
      kid_goals_other: "School bullying situation, needs confidence.",
      has_martial_arts_experience: null,
      belt: null,
      belt_other: null,
      adult_goals: [],
      adult_goals_other: "",
      adult_count: 1,
      has_read_about_bjj: true,
      found_via: ["instagram"],
      first_name: "Petra",
      last_name: "Fischer",
      email: "p.fischer@email.ch",
      phone: "+41796789012",
      whatsapp_preferred: true,
      additional_notes: "Sensitive child, please be patient.",
      best_time_to_reach: "afternoon",
      submitted_at: "2026-06-17T07:45:00.000Z",
    },
  }),
  trial("t7", {
    status: "member",
    memberPackage: "Adult Training — 12-month term",
    scheduledTrialDate: "2026-05-20",
    submittedAt: "2026-05-15T13:00:00.000Z",
    data: {
      applicant_type: "adult",
      child_count: 0,
      children: [],
      kid_goals: [],
      kid_goals_other: "",
      has_martial_arts_experience: false,
      belt: null,
      belt_other: null,
      adult_goals: ["get-fit", "find-community"],
      adult_goals_other: "",
      adult_count: 1,
      has_read_about_bjj: true,
      found_via: ["friend"],
      first_name: "Daniel",
      last_name: "Huber",
      email: "d.huber@email.ch",
      phone: "+41797890123",
      whatsapp_preferred: true,
      additional_notes: null,
      best_time_to_reach: "late-evening",
      submitted_at: "2026-05-15T13:00:00.000Z",
    },
  }),
  trial("t8", {
    status: "member",
    memberPackage: "Youth Training — 6-month term",
    scheduledTrialDate: "2026-05-10",
    submittedAt: "2026-05-01T10:00:00.000Z",
    data: {
      applicant_type: "kids",
      child_count: 1,
      children: [{ firstName: "Mia", lastName: "Schmid", ageBand: "10-13" }],
      kid_goals: ["discipline", "fitness"],
      kid_goals_other: "",
      has_martial_arts_experience: null,
      belt: null,
      belt_other: null,
      adult_goals: [],
      adult_goals_other: "",
      adult_count: 1,
      has_read_about_bjj: false,
      found_via: ["facebook"],
      first_name: "Claudia",
      last_name: "Schmid",
      email: "c.schmid@email.ch",
      phone: "+41798901234",
      whatsapp_preferred: false,
      additional_notes: null,
      best_time_to_reach: "midday",
      submitted_at: "2026-05-01T10:00:00.000Z",
    },
  }),
  trial("t9", {
    status: "member",
    memberPackage: "Adult Training — 12-month term + Youth Training — 12-month term",
    scheduledTrialDate: "2026-04-18",
    submittedAt: "2026-04-10T15:30:00.000Z",
    data: {
      applicant_type: "family",
      child_count: 1,
      children: [{ firstName: "Jonas", lastName: "Gerber", ageBand: "14-17" }],
      kid_goals: ["self-defence", "discipline"],
      kid_goals_other: "",
      has_martial_arts_experience: true,
      belt: "white",
      belt_other: null,
      adult_goals: ["continue-grow"],
      adult_goals_other: "",
      adult_count: 1,
      has_read_about_bjj: true,
      found_via: ["google"],
      first_name: "Martin",
      last_name: "Gerber",
      email: "m.gerber@email.ch",
      phone: "+41799012345",
      whatsapp_preferred: true,
      additional_notes: null,
      best_time_to_reach: "afternoon",
      submitted_at: "2026-04-10T15:30:00.000Z",
    },
  }),
  trial("t10", {
    status: "archived",
    scheduledTrialDate: "2026-03-15",
    submittedAt: "2026-03-01T09:00:00.000Z",
    data: {
      applicant_type: "adult",
      child_count: 0,
      children: [],
      kid_goals: [],
      kid_goals_other: "",
      has_martial_arts_experience: false,
      belt: null,
      belt_other: null,
      adult_goals: ["try-something-new"],
      adult_goals_other: "Moved to another city.",
      adult_count: 1,
      has_read_about_bjj: true,
      found_via: ["instagram"],
      first_name: "Nina",
      last_name: "Baumann",
      email: "n.baumann@email.ch",
      phone: "+41790123456",
      whatsapp_preferred: false,
      additional_notes: "No longer interested — relocated.",
      best_time_to_reach: "midday",
      submitted_at: "2026-03-01T09:00:00.000Z",
    },
  }),
  trial("t11", {
    status: "archived",
    submittedAt: "2026-02-20T12:00:00.000Z",
    data: {
      applicant_type: "kids",
      child_count: 1,
      children: [{ firstName: "Tim", lastName: "Roth", ageBand: "6-9" }],
      kid_goals: ["fitness"],
      kid_goals_other: "",
      has_martial_arts_experience: null,
      belt: null,
      belt_other: null,
      adult_goals: [],
      adult_goals_other: "",
      adult_count: 1,
      has_read_about_bjj: false,
      found_via: ["google"],
      first_name: "Eva",
      last_name: "Roth",
      email: "e.roth@email.ch",
      phone: "+41791239876",
      whatsapp_preferred: true,
      additional_notes: "Chose another sport.",
      best_time_to_reach: "late-morning",
      submitted_at: "2026-02-20T12:00:00.000Z",
    },
  }),
];

export const initialEvents: GymEvent[] = [
  {
    id: "e1",
    name: "Kids Graduation Day",
    date: "2026-06-08",
    time: "14:00 – 17:00",
    guestName: "Prof. Silva Cavans",
    guestInstagram: "silviocavans",
    bannerImage: "/images/about_2.jpg",
    pricing: { type: "free" },
    description:
      "Celebrate our young athletes as they receive new stripes and belts. Family and friends welcome — photos, rolling, and a short ceremony.",
    createdAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "e2",
    name: "No-Gi Fundamentals Seminar",
    date: "2026-06-14",
    time: "10:00 – 13:00",
    guestName: "Coach Aljoscha Hilse",
    guestInstagram: "joshimitsubjj",
    bannerImage: "/images/about_1.jpg",
    pricing: {
      type: "early_bird",
      earlyBirdPrice: 45,
      earlyBirdUntil: "2026-06-10",
      normalPrice: 60,
    },
    description:
      "A focused 3-hour seminar on No-Gi grips, body locks, and transitions. Open to all levels — bring rash guard and shorts.",
    createdAt: "2026-05-15T00:00:00.000Z",
  },
  {
    id: "e3",
    name: "Open Mat & BBQ",
    date: "2026-06-19",
    time: "11:00 – 15:00",
    bannerImage: "/images/about_3.jpg",
    pricing: { type: "free" },
    description:
      "Community open mat followed by a summer BBQ. All members, trial students, and friends welcome. Gi and No-Gi rolling.",
    createdAt: "2026-06-01T00:00:00.000Z",
  },
  {
    id: "e4",
    name: "Guard Passing Masterclass",
    date: "2026-07-12",
    time: "09:00 – 12:00",
    guestName: "Prof. Silva Cavans",
    guestInstagram: "silviocavans",
    bannerImage: "/images/about_1.jpg",
    pricing: {
      type: "early_bird",
      earlyBirdPrice: 80,
      earlyBirdUntil: "2026-07-01",
      normalPrice: 100,
    },
    description:
      "Deep dive into modern guard passing systems with a Cicero Costha black belt. Limited spots — Gi required.",
    createdAt: "2026-06-05T00:00:00.000Z",
  },
  {
    id: "e5",
    name: "Annual Belt Promotion Ceremony",
    date: "2026-08-23",
    time: "13:00 – 18:00",
    guestName: "Prof. Silva Cavans",
    guestInstagram: "silviocavans",
    bannerImage: "/images/about_2.jpg",
    pricing: { type: "fixed", price: 25 },
    description:
      "Our biggest event of the year — belt promotions for adults and kids, open rolling, and a guest lecture from Prof. Cavans.",
    createdAt: "2026-06-10T00:00:00.000Z",
  },
];

export const initialEventApplications: EventApplication[] = [
  {
    id: "ea1",
    eventId: "e3",
    name: "Marco Steiner",
    email: "marco.steiner@email.ch",
    phone: "+41791234567",
    paymentMethod: "on_place",
    submittedAt: "2026-06-16T10:00:00.000Z",
  },
  {
    id: "ea2",
    eventId: "e4",
    name: "Thomas Keller",
    email: "t.keller@email.ch",
    phone: "+41793456789",
    paymentMethod: "twint",
    submittedAt: "2026-06-15T14:00:00.000Z",
  },
  {
    id: "ea3",
    eventId: "e2",
    name: "Daniel Huber",
    email: "d.huber@email.ch",
    phone: "+41797890123",
    paymentMethod: "twint",
    submittedAt: "2026-06-12T09:00:00.000Z",
  },
];
